[package]
name = "qrscan"
description = "Scan a QR code in the terminal using the system camera or a given image"
version = "0.1.6"
edition = "2021"
authors = ['Arijit Basu <hi@arijitbasu.in>']
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/sayanarijit/qrscan'
homepage = 'https://github.com/sayanarijit/qrscan'
keywords = ['qrcode', 'qr', 'scan', 'reader', 'scanner']
categories = ['command-line-interface', 'command-line-utilities']

[dependencies]
qrcode = { version = "0.12.0", default-features = false, features = [
  "svg",
  "image",
] }
image = "0.23.0"
rqrr = "0.4.0"
clap = { version = "3.2.10", features = ["derive"] }
anyhow = "1.0.58"
csscolorparser = "0.6.0"
viuer = "0.5.3"

[target.'cfg(all(unix, not(macos)))'.dependencies]
nokhwa = { version = "0.9.4", features = ["input-v4l"] }

[target.'cfg(windows)'.dependencies]
nokhwa = { version = "0.9.4", features = ["input-msmf"] }

[target.'cfg(macos)'.dependencies]
nokhwa = { version = "0.9.4", features = ["input-avfoundation"] }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[dev-dependencies]
assert_cmd = "2.0.4"
