name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-github:
    name: Publish on GitHub
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-gnu, linux-musl, win-gnu, win-msvc, win32-msvc, macos]
        include:
          - BUILD: linux-gnu
            OS: ubuntu-20.04
            TOOLCHAIN: stable
            TARGET: x86_64-unknown-linux-gnu

          - BUILD: linux-musl
            OS: ubuntu-20.04
            TOOLCHAIN: stable
            TARGET: x86_64-unknown-linux-musl

          - BUILD: win-gnu
            OS: windows-2022
            TOOLCHAIN: stable
            TARGET: x86_64-pc-windows-gnu

          - BUILD: win-msvc
            OS: windows-2022
            TOOLCHAIN: stable
            TARGET: x86_64-pc-windows-msvc

          - BUILD: win32-msvc
            OS: windows-2022
            TOOLCHAIN: stable
            TARGET: i686-pc-windows-msvc

          - BUILD: macos
            OS: macos-11
            TOOLCHAIN: stable
            TARGET: x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Install musl-tools
        if: matrix.TARGET == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            --allow-unauthenticated musl-tools

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.TOOLCHAIN }}
          target: ${{ matrix.TARGET }}
          override: true
      - name: Build
        run: cargo build --release --locked --target ${{ matrix.TARGET }}

      - name: Prepare release assets
        shell: bash
        run: |
          mkdir -p release/
          cp {LICENSE,README.md} release/
          if [ "${{ matrix.OS }}" = "windows-2022" ]; then
            cp target/${{ matrix.TARGET }}/release/qrscan.exe release/
          else
            cp target/${{ matrix.TARGET }}/release/qrscan release/
          fi
          mv release/ qrscan-${{ env.RELEASE_VERSION }}/

      - name: Create release artifacts
        shell: bash
        run: |
          if [ "${{ matrix.OS }}" = "windows-2022" ]; then
            7z a -tzip "qrscan-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.zip" \
              qrscan-${{ env.RELEASE_VERSION }}/
          else
            tar -czvf qrscan-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz \
              qrscan-${{ env.RELEASE_VERSION }}/
            shasum -a 512 qrscan-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz \
              > qrscan-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}.tar.gz.sha512
          fi

      - name: Install gpg secret key
        if: matrix.OS == 'ubuntu-20.04' || matrix.OS == 'macos-11'
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Signing archive with GPG
        if: matrix.OS == 'ubuntu-20.04' || matrix.OS == 'macos-11'
        run: |
          git archive -o qrscan-${{ env.RELEASE_VERSION }}.tar.gz --format tar.gz --prefix "qrscan-${{ env.RELEASE_VERSION }}/" "v${{ env.RELEASE_VERSION }}"
          cat <(echo "${{ secrets.GPG_PASS }}") | gpg --pinentry-mode loopback --passphrase-fd 0 --detach-sign --armor "qrscan-${{ env.RELEASE_VERSION }}.tar.gz"
          mv "qrscan-${{ env.RELEASE_VERSION }}.tar.gz.asc" "source.tar.gz.asc"

      - name: Upload the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qrscan-${{ env.RELEASE_VERSION }}-${{ matrix.TARGET }}*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"

      - name: Releasing GPG signature
        uses: softprops/action-gh-release@v1
        with:
          files: |
            source.tar.gz.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
